### ISSUE TITLE
Destroyable.own supports Deferred but not documented

### ISSUE THREAD

**Issue by claudeG** [dojo/dijit#174]
Hello !

dijit.Destroyable.own source code indicates than this method accepts Deferred objects. Nevertheless this is not documented. Is there any reason for that?

Deferred reference documentation could mention it too. Any strategies, « patterns » related to the prévention of callback calls and Deferred cancellation due to the destruction of the Destroyable - widget or else-  targetted by callbacks  would be welcome too.

Thank you.

**Comment by wkeese** [comment]
It's probably just an oversite, but I should mention a standard Promise (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), unlike dojo's `promise/Promise` object, doesn't have a `cancel()` method, so calling `own()` on a standard Promise doesn't make sense.

**Comment by jithendraTR** [comment]
Hi Team, We are facing one issue with latest dojo and dijit upgrade to 1.17.3, we have our calendar view using widgets to display labels under each date, so when we are routing back (using router.go) to other view dojo is trying to destroy the widgets in calendar page and the below error was getting occurred with page getting struck without navigating to other view, with the older version of dojo/dijit like 1.9.X there wasn't any issue and navigation was working fine, if you could please check and let us know how this can be resolved it will be of great help and much appreciated. Thanks a lot in advance.

Error:
TypeError: handle[destroyMethodName] is not a function
    at Object.<anonymous> (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:20675:31)
    at Object.dispatcher [as destroy] (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:8640:29)
    at Object._destroyRenderer (https://xxxxxxxxxxx.com/current/js/dojox/calendar/ViewBase.js:2:10728)
    at Object.destroy (https://xxxxxxxxxxx.com/current/js/dojox/calendar/ViewBase.js:2:1306)
    at Object.inherited (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:11345:30)
    at Object.destroy (https://xxxxxxxxxxx.com/current/js/dojox/calendar/MatrixView.js:4:2908)
    at Object.advice (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:8666:23)
    at Object.dispatcher [as destroy] (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:8646:39)
    at Object.destroyRecursive (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:19994:9)
    at destroy (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:20017:8)TypeError: handle[destroyMethodName] is not a function
    at Object.<anonymous> (https://xxxxxxxxxxx.com/current/js/xx/xxx/xxxxxx.js:1883:26)
    at signalListener (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:7263:21)
    at Deferred.then.promise.then (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:7484:5)
    at Object.<anonymous> (https://xxxxxxxxxxx.com/current/js/xx/xxx/xxxxxx.js:1874:53)
    at signalListener (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:7263:21)
    at Deferred.then.promise.then (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:7484:5)
    at Object._go (https://xxxxxxxxxxx.com/current/js/xx/xxx/xxxxxx.js:1869:55)
    at Object.<anonymous> (https://xxxxxxxxxxx.com/current/js/xx/xxx/xxxxxx.js:1557:10)
    at Object.<anonymous> (https://xxxxxxxxxxx.com/current/js/xx/xxx/xxxxxx.js:3267:10)
    at Evented.dispatcher [as on/dojo/hashchange] (https://xxxxxxxxxxx.com/current/js/dojo/dojo.js:8653:39) 

Error snapshot:
![image](https://user-images.githubusercontent.com/88323184/214587725-4a9a46ed-8245-4ece-b7a6-4f8ca53b8a46.png)
